spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatapp?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: chatapp
    password: chatapp
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: info
chatapp:
  mvc:
    allowedOrigins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
  stomp:
    disconnectDelay: 900 # 30 * 30
    httpMessageCacheSize: 1000
    streamBytesLimit: 524288 # 512 * 1024
